build:
	@make -C .. --no-print-directory

depend:
	@make -C .. --no-print-directory depend

help:
	@make -C .. --no-print-directory help

debug:
	@make -C .. --no-print-directory debug

nodebug:
	@make -C .. --no-print-directory nodebug

push:
	@make -C .. --no-print-directory push
